spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.129:3306/realmall_pms?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    # 服务名
    name: realmall-product
alibaba:
  cloud:
    access-key: LTAI5tA4nZFfpgcg75yH13T6
    secret-key: Z4zErCGevvU7jSipPucYeAkcERVp2E
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      #logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
logging:
  level:
    com.liu.realmall.product.dao: debug
server:
  port: 8088


